// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rnormCube
SEXP rnormCube(SEXP varp1, SEXP varp2, SEXP varp3);
RcppExport SEXP tensorBSS_rnormCube(SEXP varp1SEXP, SEXP varp2SEXP, SEXP varp3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varp1(varp1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type varp2(varp2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type varp3(varp3SEXP);
    rcpp_result_gen = Rcpp::wrap(rnormCube(varp1, varp2, varp3));
    return rcpp_result_gen;
END_RCPP
}
// eigenVectors
SEXP eigenVectors(SEXP varx);
RcppExport SEXP tensorBSS_eigenVectors(SEXP varxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenVectors(varx));
    return rcpp_result_gen;
END_RCPP
}
// symmetricPower
SEXP symmetricPower(SEXP varx, SEXP varr);
RcppExport SEXP tensorBSS_symmetricPower(SEXP varxSEXP, SEXP varrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varr(varrSEXP);
    rcpp_result_gen = Rcpp::wrap(symmetricPower(varx, varr));
    return rcpp_result_gen;
END_RCPP
}
// mFOBIMatrix
SEXP mFOBIMatrix(SEXP varx);
RcppExport SEXP tensorBSS_mFOBIMatrix(SEXP varxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    rcpp_result_gen = Rcpp::wrap(mFOBIMatrix(varx));
    return rcpp_result_gen;
END_RCPP
}
// mFOBIMatrixNorm
SEXP mFOBIMatrixNorm(SEXP varx);
RcppExport SEXP tensorBSS_mFOBIMatrixNorm(SEXP varxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    rcpp_result_gen = Rcpp::wrap(mFOBIMatrixNorm(varx));
    return rcpp_result_gen;
END_RCPP
}
// mJADEMatrix
SEXP mJADEMatrix(SEXP varx, SEXP vari, SEXP varj, SEXP varcov);
RcppExport SEXP tensorBSS_mJADEMatrix(SEXP varxSEXP, SEXP variSEXP, SEXP varjSEXP, SEXP varcovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vari(variSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varj(varjSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varcov(varcovSEXP);
    rcpp_result_gen = Rcpp::wrap(mJADEMatrix(varx, vari, varj, varcov));
    return rcpp_result_gen;
END_RCPP
}
// matrixCovariance
SEXP matrixCovariance(SEXP varx);
RcppExport SEXP tensorBSS_matrixCovariance(SEXP varxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCovariance(varx));
    return rcpp_result_gen;
END_RCPP
}
// mAutoCovMatrix
SEXP mAutoCovMatrix(SEXP varx, SEXP varlag);
RcppExport SEXP tensorBSS_mAutoCovMatrix(SEXP varxSEXP, SEXP varlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varlag(varlagSEXP);
    rcpp_result_gen = Rcpp::wrap(mAutoCovMatrix(varx, varlag));
    return rcpp_result_gen;
END_RCPP
}
// mTGFOBIMatrix
SEXP mTGFOBIMatrix(SEXP varx, SEXP varlag);
RcppExport SEXP tensorBSS_mTGFOBIMatrix(SEXP varxSEXP, SEXP varlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varlag(varlagSEXP);
    rcpp_result_gen = Rcpp::wrap(mTGFOBIMatrix(varx, varlag));
    return rcpp_result_gen;
END_RCPP
}
// mTGJADEMatrix
SEXP mTGJADEMatrix(SEXP varx, SEXP vari, SEXP varj, SEXP varlags);
RcppExport SEXP tensorBSS_mTGJADEMatrix(SEXP varxSEXP, SEXP variSEXP, SEXP varjSEXP, SEXP varlagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type varx(varxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vari(variSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varj(varjSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varlags(varlagsSEXP);
    rcpp_result_gen = Rcpp::wrap(mTGJADEMatrix(varx, vari, varj, varlags));
    return rcpp_result_gen;
END_RCPP
}
